sbtpitchplay:
  image: pitchplay/scala-dev:jdk8
  command: "~scripted"
  volumes:
    - .:/usr/src/app
  volumes_from:
    - ivycache
  log_opt:
    max-size: "100k"
    max-file: "1"
ivycache:
  image: busybox
  volumes:
    - ~/.ivy2:/root/.ivy2
